### PR TITLE
Added yearMin and yearMax options, created a simple demo and linted code

### PR DESCRIPTION
**Pull request by fbaiodias**
Hey!

Here's a few changes we needed at @sinfo, might be useful for other people as well.

You can now run the demo with: 

```
npm run demo
```

And pass year limits like:

``` js
var input = new DateView({
  label: 'Birth date',
  name: 'birthDate',
  yearMax: 1940,
  yearMax: 2000
});
```

Thanks!

### CODE REVIEW

**Comment by mikehedman** [comment]
@xicombd Hi, sorry, I just saw this PR (odd that GitHub didn't mail me!).  I'm traveling, so it'll take me a couple days before I can review.  Thanks!

**Comment by fbaiodias** [comment]
No problem, have a nice trip! :smiley:

**Comment by mikehedman** [comment]
@xicombd Francisco, thanks for the PR!  I've published the new code to NPM: https://www.npmjs.com/package/ampersand-date-view.
Mike

**Comment by fbaiodias** [comment]
Thanks Mike!

**Pull request merged**
